server:
  port: 8181

spring:
  application:
    name: bookcatalog

  # PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/bookdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  # Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration

  # JPA
  jpa:
    hibernate:
      ddl-auto: none # Using 'none' because Flyway handles schema management
    show-sql: true   # Useful for debugging SQL queries

  # Redis
  data:
    redis:
      host: localhost
      port: 6379
      time-to-live: 60000

# Logging configuration specific to Flyway
logging:
  level:
    org:
      flywaydb: DEBUG # Set Flyway logging level to DEBUG for detailed migration info